phases: 
  install: 
    runtime-versions: 
      nodejs: 20 
    commands: 
    - echo "Installing dependencies" 
    - npm install
  build: 
    on-failure: ABORT
    commands: 
      - echo "Building application" 
      - npm run build
  post_build: 
    commands: 
    - echo "Build completed" 
    - echo "Copying files to S3" 
    - aws s3 cp dist s3://learn-teste/ --recursive
artifacts: 
  files: 
  - '**/*' 
  base-directory: dist
cache:
  paths: 
  - 'node_modules/**/*'